#lang racket

;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(define (sol)
  (define (help prev curr acc)
    (if (> curr 4000000)
        acc
        (if (even? curr)
            (help curr (+ prev curr) (+ acc curr))
            (help curr (+ prev curr) acc))))
  (help 0 1 0))
(sol) ; 4613732